### ISSUE TITLE
Write a (step-by-step) installation instruction for windows users

### ISSUE THREAD

**Issue by AlexDo1** [VForWaTer/metacatalog#108]
I have problems following the current [installation instructions](https://github.com/VForWaTer/metacatalog/blob/master/docs/source/home/install.rst) for metacatalog (I don´t have much experience with postgreSQL and databases).
I commented on the latest [commit](https://github.com/VForWaTer/metacatalog/commit/eec46d6c7974e851b34cdd07a363afb49628823e) at the lines where I had problems.

Once I managed to finish the installation, I can write a step-by-step instruction for windows.

**Comment by mmaelicke** [comment]
Great. I just replied to your comments. Then, we can use this issue to solve all the problems in the instructions.
