### ISSUE TITLE
Add citation to the Person model

### ISSUE THREAD

**Issue by AlexDo1** [VForWaTer/metacatalog#119]
> 1. `citation` is commented out because the add_person() function does not have an argument `citation` and trying to use the argument gives the error `TypeError: add_person() got an unexpected keyword argument 'citation'`

> Good to know. Can you please open an issue in metacatalog to add that option?

_Originally posted by @mmaelicke in https://github.com/VForWaTer/scripts/issues/3#issuecomment-786581933_

1. Add a `citation` argument/column to the Person model.
2. Update the add_person() function to add a citation to a person.

**Comment by mmaelicke** [comment]
If you want to do it yourself, you can assign yourself. Otherwise, if I should do it, then just assign me.

**Comment by AlexDo1** [comment]
The Person model already got the attribute `attribution`, where the citation information about a person should be stored.
