### ISSUE TITLE
Add the EntryGroup 'Split dataset' to metacatalog

### ISSUE THREAD

**Issue by AlexDo1** [VForWaTer/metacatalog#122]
As with the LUBW level data, where the temporal resolution of the data changes as it progresses, sometimes the data needs to be split. 
We need to implement the new EntryGroup type `Split dataset` to group these entries with a changing data storage system.

(https://github.com/VForWaTer/scripts/issues/7)

**Comment by AlexDo1** [comment]
I think I can do that.

Do you have a better description for the EntryGroup type or is this description ok?

| name  | description |
| ------------- | ------------- |
| Split dataset  | A split dataset groups a number of identical datasets that have to be split e.g. in case of different time scale resolution.  |

**Comment by mmaelicke** [comment]
The description is fine for now, I am just wondering if it might be preferable to have no whitespaces in the name...
So using `SplitDataset` instead of `Split dataset`

**Comment by mmaelicke** [comment]
No, let's try going for `Split dataset`
