### ISSUE TITLE
unittest Fail

### ISSUE THREAD

**Issue by mmaelicke** [VForWaTer/metacatalog#129]
@AlexDo1 currently, the unittest are failing because of this line:

https://github.com/VForWaTer/metacatalog/blob/8231b7e6989f4bc968341d7dd92bf7c5353fa932/metacatalog/ext/io/reader.py#L65

I think you forgot to rename this `df` here, because it is only crated 4 lines above in the other if branch. Maybe you meant the `column_names` or `df_sql` here?

**Comment by AlexDo1** [comment]
I have been working on this recently and this is actually not my last commit, sorry.
I just pushed a new commit on Github that should pass the unittest.

**Comment by AlexDo1** [comment]
Just noticed that the unittest in github does not pass, locally on my PC the tests work.
The error message in the [test ](https://github.com/VForWaTer/metacatalog/pull/126/checks?check_run_id=2600554046) is:
`Error: : Operation not possible.
No IO interface activated. Run metacatalog.ext.extension('io', InterfaceClass) to register`

Do I have to run `metacatalog.ext.extension('io', InterfaceClass)` for the unittest to work in github?

**Comment by mmaelicke** [comment]
Yes. I quickly added the activation to the CI in https://github.com/VForWaTer/metacatalog/commit/c0b539b95bf1108209e0c939643f17c420a8edcd

If the tests in master pass, you can merge the changes into your branch and it should work.
