### ISSUE TITLE
Wrong unit for electrical conductivity in units.csv

### ISSUE THREAD

**Issue by AlexDo1** [VForWaTer/metacatalog#161]
The unit for electrical conductivity in [units.csv](https://github.com/VForWaTer/metacatalog/blob/master/metacatalog/data/units.csv) is `electrical conductivity`, but must be `mS/cm` or `μS/cm`:
https://github.com/VForWaTer/metacatalog/blob/e9634a950c6e760ff0803ff1ec65aa77df69eebd/metacatalog/data/units.csv#L26

We need a database revision to fix this.

**Comment by AlexDo1** [comment]
I would suggest using `mS/cm`, as this is the unit used in the Bühlot data set, but also the [Ott CTD Sensor](https://www.ott.com/products/water-level-1/ott-ctd-sensor-37/), for example, measures in mS/cm by default.
But of course this depends on the type of application, but `mS/cm` seems to me a good standard.

**Comment by mmaelicke** [comment]
I am fine with `mS/cm`, data using `µS` can easily be converted. Do you want to PR a database revision or shall I do that?
