### ISSUE TITLE
Refactor aliased Keywords to Key-Value Pairs

### ISSUE THREAD

**Issue by mmaelicke** [VForWaTer/metacatalog#17]
Already for Sap Flow data and Eddy data the proposed controlled Keyword concept is not working anymore. I will refactor it into:

a) controlled keywords fed from different dictionaries, which just tag an `Entry` to apply keyword filters.
b) an arbitrary amount of key-value pairs that can be linked to an `Entry`. I will test out some stemming libraries in Python to standardize the keys to a specific amount. NoSQL would be great here, but that's not a way to go.

One example that did not work anymore was the metadata of sap flow sensors, how deep they are built into a tree. If I would introduce a custom keyword that describes the horizontal depth of a tree in a standardized manner it might work for metacatalog, but when exported to `ISO19115` we would lose this vital information unless we register this as an official keyword of our self-hosted dictionary. That is not the way to go for now. The other possibility would be to put vital metadata into the comments, which we try to overcome with the new db scheme.

@MarcusStrobl do you have any quick comments on this? Any alternative, which can be implemented until next week?

**Comment by MarcusStrobl** [comment]
You say we should use the keywords following `ISO19115` and custom keywords to improve the filter, right? 
Having vital metadata in the comments is a hack I'd prefer to avoid. 
Why not having two separate lists (or one list with a flag to distinguish standard from custom keywords)?
