### ISSUE TITLE
Close RESTful & ResultSetList issues and pull requests

### ISSUE THREAD

**Issue by AlexDo1** [VForWaTer/metacatalog#173]
Some of the open issues and PRs are related to each other:
- #85: will be closed via #131
  - PR is currently closed, @mmaelicke wanted to come back after #140 is finished.
- #140: linked PR #159 is still open 
  - e2e tests fail
  - linked to issue #160 
- #160
  - harmonize data by cutting the extent and aggregate resolution

To close these issues and pull requests, we can do the work in the following order:
- [ ] #160 
- [ ] #140 via #159
- [ ] #85 via #131

**Comment by mmaelicke** [comment]
There are no current plans to introduce REST api as a core feature.
