### ISSUE TITLE
Finalize location implementation

### ISSUE THREAD

**Issue by AlexDo1** [VForWaTer/metacatalog#189]
In the V-For-WaTer meeting on Tuesday 12/12/2023, we will discuss how we want to finally implement locations. We should make adjustments based on the results of the discussion and also update the documentation.

For that we, should also keep this comment in mind:

> I guess, with this in place, we can make the location column nullable and remove the point for RADKLIM data. The view should then generate the centroid as a point for the `point_location` view column, right?
> 
> I guess the key here is the `area` column, as we can request the geometries depending on the Map zoom level. For a small zoom level (ie 2, almost world-view) the Geoserver layer should use only `geom` that have a **minimum** size, effectively shrinking the rectangle around BaWü to its centroid, but at the same time the Radklim can still be viewed. If we are closer (ie. zoom level 12), BaWür would use the POLYGON as well.
> 
> So to come back to your question: we add `location` as point, whenever that makes sense, we add the `geom`, if there is a Non-Point representation of the spatial domain of measurements (ie. catchment) and we set the geometry inside the spatial scale of the datasource as a bounding box (effectively the extent of all measurements) as required by INSPIRE/ISO 19115. 
> The distinction between the datasource.spatial_scale.extent and the entry.geom is not 100% clear, I guess, and we can discuss this. My 2 cents on this: the `geom` is the area, that is represented by the measurements (so its about the data), while the spatial extent is the covered area (so its about the metadata).

_Originally posted by @mmaelicke in https://github.com/VForWaTer/metacatalog/issues/186#issuecomment-1344156932_

**Comment by mmaelicke** [comment]
For reference, we decided the drop the distinction between data representative geometries and metadata extent, as there are hardly any use-cases for this.
This means, the `geom` will stay deprecated and this issue can be closed.
