### ISSUE TITLE
Details thesaurus_id bug

### ISSUE THREAD

**Issue by AlexDo1** [VForWaTer/metacatalog#192]
There are bugs in the [Details](https://github.com/VForWaTer/metacatalog/blob/master/metacatalog/models/details.py) model.

1. Column `thesaurus_id` should link to `keywords.id` to relate individual details to thesaurus values. We could then also rename column `thesaurus_id` to `keyword_id` for clarity:
https://github.com/VForWaTer/metacatalog/blob/5fc68a25d58698b9369ae6d653f9717157189333/metacatalog/models/details.py#L79

2. We also need to update the relationship for keywords here:
https://github.com/VForWaTer/metacatalog/blob/5fc68a25d58698b9369ae6d653f9717157189333/metacatalog/models/details.py#L83

3. Another related bug is, that when initializing a new database instance, `keywords.thesaurus_id` is always `[null]`. This should link to the thesaurus to which the keyword belongs to (in our case always `1`, as we currently only have the GCMD thesaurus).

**Comment by mmaelicke** [comment]
This is on purpose. The `Detail` does **not** reference controlled keywords, but can rather itself be **part** of a thesauri. If that is the case, it can be referenced here, if metacatalog contains the thesauri information.
I guess the main question is: are there `Detail.key` values, which are also controlled keywords. In that case, the semantics matter: Do we then duplicate the key into the keywords table and reference it to the `Entry`? Then we can remove the lines above. 
Or: If we want all controlled keywords of an entry, we need to add the Details, which reference a Thesauri. These are assumed to be keyword as well, without being stored in keywords. The advantage is, that users can tag entries with keywords, which are not added to metacatalog. The only thing we need then is the metadata about the thesauri.

I think the second approach is the better one. This is also already implemented and this issue can be closed. If you don't agree @AlexDo1 , please reopen the issue.
