### ISSUE TITLE
Move default branch to `main`

### ISSUE THREAD

**Issue by mmaelicke** [VForWaTer/metacatalog#242]
@AlexDo1  I create a new branch called `main` and make that the default branch. If you are currently working on a local copy of `master` you should push these changes into a new branch, that will then be merged into `main` instead of `master`

**Comment by AlexDo1** [comment]
Okay! I have no local changes.  
I released version 0.7.2 on `master` earlier, but that's missing on the new `main` branch. On pypi v0.7.2 is already puplished, I will just change `__version__.py` to v0.7.2, then everything should be fine and we can continue working on the `main` branch.

**Comment by mmaelicke** [comment]
I saw that too, did you maybe forget to push that online?

**Comment by AlexDo1** [comment]
Yes, I probably forgot that.  
Do I have to run any git commands to make the `main` branch the new default branch locally?

**Comment by mmaelicke** [comment]
nope. You can just checkout the `origin/main`. You might need a `git fetch` if vscode is not aware of that branch. 
Once on `main` you can delete your local `master` using `bait branch -d master`

**Comment by AlexDo1** [comment]
Okay perfect, I did that.  
I guess we can mark this issue as closed.
