### ISSUE TITLE
`Entry.contributors` returns `PersonAssociations` instead of `Person`

### ISSUE THREAD

**Issue by mmaelicke** [VForWaTer/metacatalog#249]
I just found out that, `Entry.contributors` stills returns `PersonAssociations` instead of `Person` objects:
![Bildschirmfoto vom 2023-01-31 14-16-16](https://user-images.githubusercontent.com/23619690/215770816-60dd58d2-b05d-46cf-a9cf-63c154d3bda1.png)

_Originally posted by @AlexDo1 in https://github.com/VForWaTer/metacatalog/issues/248#issuecomment-1410333968_

**Comment by mmaelicke** [comment]
I would close this without implementing it, as this is actually not a bug. The `PersonAssociation` further relates the `PersonRoles`. If we directly load the `Person`, we loose the information on the role with which the person is related to the `Entry`.

However, accessing the persons is trivial: 

```python
[pa.person for pa in entry.contributors]
```
returns a list `Persons`. 
A drawback is, that the `PersonAssociation.to_dict` method always includes the `Entry`. We could change that to only inlcude the Entry if `deep=True`.  Then this code would produce better output:


```python
[pa.to_dict() for pa in entry.contributors]
```

```
[{
  "person": `Person`,
  "role": `PersonRole`,
  "order": `Number`
}]
```

**Comment by AlexDo1** [comment]
Yes that's good.

The fact `Persons` are still easily accessible through `PersonAssociation.person` solves the issue for me.

The changes to `PersonAssociation.to_dict` to only include the `Entry` with `deep=True` would still be nice..
