### ISSUE TITLE
`api.add_entry` misses `is_partial` flag to create partial entries.

### ISSUE THREAD

**Issue by mmaelicke** [VForWaTer/metacatalog#257]
@AlexDo1, what was your workflow so far to add partial entries using the API? Do I miss something, but it seems like that is not possible.

**Comment by AlexDo1** [comment]
That's true, the parameter `isPartial` is missing in `api.add_entry()`.  
Nevertheless, I used the `isPartial` parameter when I uploaded the eddy covariance data, and it looks like it worked then:
![Bildschirmfoto vom 2023-02-08 09-48-33](https://user-images.githubusercontent.com/23619690/217481089-8309ef3b-5383-4c3b-9187-c16a8d45e55d.png)

**Comment by mmaelicke** [comment]
Ok the is_partial is set over `**kwargs`, thus is is only about adding docs and a new argument to set it explicitly.
