### ISSUE TITLE
Strange geneic name

### ISSUE THREAD

**Issue by MarcusStrobl** [VForWaTer/metacatalog#29]
Is there a reason to write `geneic` in `geometry_data.py` or is this just a typo?

```
class GenericGeometryData(Base):
    __tablename__ = 'geneic_geometry_data'
```

**Comment by mmaelicke** [comment]
Oh wow, that is a typo that could survive for some time. Like an embarrassing amount of time.
I will fix it with the next release. If you need the table renamed earlier in V-FOR-WaTer, you can go ahead as I am not working on that table or model.
