### ISSUE TITLE
The new ISO extension is not visible in the docs

### ISSUE THREAD

**Issue by mmaelicke** [VForWaTer/metacatalog#293]
@AlexDo1 you wanna fix?

**Comment by AlexDo1** [comment]
I noticed the same yesterday.  
Maybe we can fix this in #290 before we merge.  
I also made a comment about failing documentation CI here: https://github.com/VForWaTer/metacatalog/pull/290#issuecomment-1453602499

I would like to fix this, but I'm not sure where to start.
