### ISSUE TITLE
Nullable columns in eddy_data.py

### ISSUE THREAD

**Issue by AlexDo1** [VForWaTer/metacatalog#3]
Which columns should be `nullable` in [eddy_data.py](https://github.com/VForWaTer/metacatalog/blob/master/metacatalog/models/eddy_data.py) )?

_Originally posted by @mmaelicke in https://github.com/VForWaTer/metacatalog/pull/2_

**Comment by mmaelicke** [comment]
Moved this to mid-term, as the whole default-Eddy-columns thing is **way** more complex than expected

**Comment by mmaelicke** [comment]
I am thinking about rather introducing a new `EntryGroupType` called `dataset`. Other that `composite` this will **always** load the other records as well. I am not sure how the Eddy-Data can else fit into the metadata-model. This is still in discussion and I will make a final decission soon

**Comment by mmaelicke** [comment]
@AlexDo1 I think we can reuse this issue to implement a roadmap for adding eddy data here in this issue as this is kind of related, or at least will be solved with Eddy finally in the database.
We can have a call next week and add some to-dos here.

**Comment by mmaelicke** [comment]
I guess this is done now
