### ISSUE TITLE
Add a e2e-test for composites

### ISSUE THREAD

**Issue by mmaelicke** [VForWaTer/metacatalog#60]
We need a test pipeline for `EntryGroups`

* [x] create a Project and find by project
* [ ] create a Composite and find by composite
* [ ] use API and models for finding
* [ ] add a partial Entry to a composite and test if it is not found by `api.find_entry`

**Comment by mmaelicke** [comment]
@AlexDo1 I think the tests above have been implemented at some point. We have test_array_type and test_groups_projects. I think most of the stuff is tested. Could you go through the mentioned test files and check what is covered today?
Just post the line of the tests here and if everything is checked, we can close this issue

**Comment by AlexDo1** [comment]
> We need a test pipeline for `EntryGroups`
> 
> * [x]  create a Project and find by project
> * [ ]  create a Composite and find by composite
> * [ ]  use API and models for finding
> * [ ]  add a partial Entry to a composite and test if it is not found by `api.find_entry`

We got tests covering the **creation** of Composite EntryGroups. We are also testing if we can **find** composite datasets, but we do not check if we can find **by** composite (1.1, 1.2).

I think we use the API for finding but we are not using models for finding.

We also add a partial Entry to a Composite EntryGroup which is only found if `include_partial=True` (1.3).


1.1 Add Composite dataset: https://github.com/VForWaTer/metacatalog/blob/0d3bacbe2ced1164ccac7731c317d18dccf775d9/metacatalog/test/test_api_add_find.py#L144-L152
1.2 Create composite & find: https://github.com/VForWaTer/metacatalog/blob/0d3bacbe2ced1164ccac7731c317d18dccf775d9/metacatalog/test/test_groups_projects.py#L45-L49
https://github.com/VForWaTer/metacatalog/blob/0d3bacbe2ced1164ccac7731c317d18dccf775d9/metacatalog/test/test_groups_projects.py#L98
3. add a partial Entry to a composite and test if it is not found by `api.find_entry`:
https://github.com/VForWaTer/metacatalog/blob/0d3bacbe2ced1164ccac7731c317d18dccf775d9/metacatalog/test/test_groups_projects.py#L83
https://github.com/VForWaTer/metacatalog/blob/0d3bacbe2ced1164ccac7731c317d18dccf775d9/metacatalog/test/test_groups_projects.py#L113

**Comment by mmaelicke** [comment]
Thank you very much! Then I guess it's fine and we can close this issue
